CREATE TABLE KULLANICI(
TCNo VARCHAR(11) NOT NULL,
Ad VARCHAR(30) NOT NULL,
Soyad VARCHAR(30) NOT NULL,
DogumT DATE NOT NULL,
Adres VARCHAR(200),
Cinsiyet CHAR NOT NULL,
Boy INT,
Kilo INT,
Sifre VARCHAR(30) NOT NULL,
CONSTRAINT PKKUL PRIMARY KEY(TCno)
);


CREATE TABLE ILAC(
IlacId UUID NOT NULL,
IlacAdi VARCHAR(30) NOT NULL,
Prospektus TEXT,
Mg INT NOT NULL,
Ac_Tok CHAR,
Resim TEXT,
CONSTRAINT ILPK PRIMARY KEY(IlacId));


CREATE TABLE ASI(
AsiId UUID NOT NULL,
AsiAdi VARCHAR(30) NOT NULL,
YapilmaYasi INT,
CONSTRAINT ASIPK PRIMARY KEY(AsiId)
);


CREATE TABLE HASTANE(
HastaneId UUID NOT NULL,
HastaneAd VARCHAR(60) NOT NULL,
Adres VARCHAR(200),
CONSTRAINT HASPK PRIMARY KEY(HastaneId)
);


CREATE TABLE DOKTOR(
TCNo VARCHAR(11) NOT NULL,
HastaneId UUID NOT NULL,
Bolum VARCHAR(60) NOT NULL,
CONSTRAINT TCFK FOREIGN KEY(TCNo) REFERENCES KULLANICI(TCNo),
CONSTRAINT HASFK FOREIGN KEY(HastaneId) REFERENCES HASTANE(HastaneId)
);

CREATE TABLE KULLANIR(
TCNo VARCHAR(11) NOT NULL,
IlacId UUID NOT NULL,
Siklik INT NOT NULL,
KullanmaSayisi INT NOT NULL,
CONSTRAINT TCFK FOREIGN KEY(TCNo) REFERENCES KULLANICI(TCNo),
CONSTRAINT ILACFK FOREIGN KEY(IlacId) REFERENCES ILAC(IlacId)
);

CREATE TABLE YAPTIRIR(
TCNo VARCHAR(11) NOT NULL,
AsiId UUID NOT NULL,
YapilmaTarihi DATE,
CONSTRAINT TCFK FOREIGN KEY(TCNo) REFERENCES KULLANICI(TCNo),
CONSTRAINT ASFK FOREIGN KEY(AsiId) REFERENCES ASI(AsiId)
);

CREATE TABLE RANDEVU(
KullaniciTc VARCHAR(11) NOT NULL,
DoktorTc VARCHAR(11) NOT NULL,
RandevuAdi VARCHAR(60) NOT NULL,
Gitti_mi CHAR NOT NULL,
Tarih DATE NOT NULL,
CONSTRAINT KULTCFK FOREIGN KEY(KullaniciTc) REFERENCES KULLANICI(TCNo),
CONSTRAINT DOKTCFK FOREIGN KEY(DoktorTc) REFERENCES KULLANICI(TCNo)
);

CREATE TABLE YAZAR(
KullaniciTc VARCHAR(11) NOT NULL,
DoktorTc VARCHAR(11) NOT NULL,
IlacId UUID NOT NULL,
YazTarih DATE NOT NULL,
CONSTRAINT KULTCFK FOREIGN KEY(KullaniciTc) REFERENCES KULLANICI(TCNo),
CONSTRAINT DOKTCFK FOREIGN KEY(DoktorTc) REFERENCES KULLANICI(TCNo),
CONSTRAINT ILACFK FOREIGN KEY(IlacId) REFERENCES ILAC(IlacId)
);

